### ISSUE TITLE
Multi-lang Component Postgres Roadmap

### ISSUE THREAD

**Issue by ajhool** [pulumi/pulumi-aws-quickstart-aurora-postgres#10]
- [ ] Parameters
   - [x] Network configuration
     - [x] VPCID 
     - [x] Subnet1ID
     - [x] Subnet2ID
     - [x] DBSecurityGroupId
  - [ ] Database configuration
    - [x] DBName
    - [x] DBAutoMinorVersionUpgrade
    - [x] DBBackupRetentionPeriod
    - [x] DBEngineVersion
    - [x] DBInstanceClass
    - [x] DBMasterUsername
    - [x] DBMasterUserPassword
    - [x] DBPort
    - [ ] DBAccessCIDR
    - [ ] DBMultiAZ
    - [ ] DBAllocatedStorageEncrypted
    - [ ] DBExportLogToCloudwatch
    - [x] EnableEventSubscription
    - [x] SnsNotificationEmail
  - [ ] Database tags (optional)
    - [ ] EnvironmentStage
    - [ ] Application
    - [ ] ApplicationVersion
    - [ ] ProjectCostCenter
    - [ ] Confidentiality
    - [ ] Compliance
- [x] Code Sweep
  - [x] Improve function names
  - [x] Improve code layout
  - [x] Add comments, remove old comments, etc.
- [x] Test Deployments
  - [x] Single-AZ (private)
  - [x] Multi-AZ (private)
  - [x] Single-AZ (public)
  - [x] Multi-AZ (public)
- [x] Documentation
  - [x] Basic README pointing to AWS Quickstart Guide
  - [x] Example Usage (maybe use the Test Deployments, above)
  - [x] Does Pulumi have an automated tool for uploading docs onto pulumi's website? (Eg. are these vpc docs coming from a github repo somewhere? https://www.pulumi.com/docs/reference/pkg/aws/ec2/vpc/    )
